### Tutorial on how to use the Mixing Matrix

In [43]:
import numpy as np
from non_parametric_ML_compsep import *

In [44]:
# choose frequencies
freqs = np.array([40, 50, 60, 100, 140])
ncomp = 3
pos_special_freqs = np.array([-1, 0])

In [45]:
initB = InitMixingMatrix(freqs, ncomp, pos_special_freqs)
init_params = initB.init_params()

In [25]:
init_params

array([[1.91733692, 1.34513969],
       [4.70174773, 3.29858953],
       [9.45744151, 6.63502582]])

In [46]:
B = MixingMatrix(freqs, ncomp, init_params, pos_special_freqs)

In [47]:
B_cmb = B.get_B_cmb()
B_fgs = B.get_B_fgs()
B_all = B.get_B()

In [48]:
print(B_all)

[[1.         0.         1.        ]
 [1.         0.15071531 1.42538127]
 [1.         0.20273315 1.91733692]
 [1.         0.49714796 4.70174773]
 [1.         1.         0.        ]]


In [49]:
B.update_params(B.params+1)

array([[0.15071531, 1.42538127],
       [0.20273315, 1.91733692],
       [0.49714796, 4.70174773]])