## Tutorial on how to use the Mixing Matrix

In [14]:
import numpy as np
from micmac import *

#### Set required parameters
(In actual applications they'll come from the instrument / input data)

In [15]:
# choose frequencies
freqs = np.array([40, 50, 60, 100, 140])
# choose number of components
ncomp = 3
# choose frequencies at which we have one fgs and the others zero
# in MixingMat columns first synch, then dust
pos_special_freqs = np.array([0, -1])

#### Initialize parameters of the Mixing Matrix
These are the true values (done with values coming from SEDs of a MBB and a PL).
Alternativly one can skip this step and set customized values.

In [16]:
initB = InitMixingMatrix(freqs, ncomp, pos_special_freqs)
init_params = initB.init_params()
init_params

array([[ 1.42538127, 14.44037732],
       [ 1.91733692,  8.59386185],
       [ 4.70174773,  2.1780368 ]])

#### Build the Mixing Matrix

In [17]:
B = MixingMatrix(freqs, ncomp, init_params, pos_special_freqs)
B_cmb = B.get_B_cmb()
B_fgs = B.get_B_fgs()
B_all = B.get_B()

In [18]:
print(B_all)

[[ 1.          1.          0.        ]
 [ 1.          1.42538127 14.44037732]
 [ 1.          1.91733692  8.59386185]
 [ 1.          4.70174773  2.1780368 ]
 [ 1.          0.          1.        ]]


#### Update parameters of the Mixing Matrix

In [19]:
new_params = B.params+1
B.update_params(new_params)
B.params

array([[ 2.42538127, 15.44037732],
       [ 2.91733692,  9.59386185],
       [ 5.70174773,  3.1780368 ]])

In [20]:
B_all_new = B.get_B()
B_all_new

array([[ 1.        ,  1.        ,  0.        ],
       [ 1.        ,  2.42538127, 15.44037732],
       [ 1.        ,  2.91733692,  9.59386185],
       [ 1.        ,  5.70174773,  3.1780368 ],
       [ 1.        ,  0.        ,  1.        ]])