## Tutorial on how to use the Mixing Matrix

In [39]:
import numpy as np
from non_parametric_ML_compsep import *

#### Set required parameters
(In actual applications they'll come from the instrument / input data)

In [40]:
# choose frequencies
freqs = np.array([40, 50, 60, 100, 140])
# choose number of components
ncomp = 3
# choose frequencies at which we have one fgs and the others zero
pos_special_freqs = np.array([-1, 0])

#### Initialize parameters of the Mixing Matrix
This is done with values coming from SEDs of a MBB and a PL.
Alternativly one can skip this step and set customized values.

In [41]:
initB = InitMixingMatrix(freqs, ncomp, pos_special_freqs)
init_params = initB.init_params()
init_params

array([[0.15071531, 1.42538127],
       [0.20273315, 1.91733692],
       [0.49714796, 4.70174773]])

#### Build the Mixing Matrix

In [42]:
B = MixingMatrix(freqs, ncomp, init_params, pos_special_freqs)
B_cmb = B.get_B_cmb()
B_fgs = B.get_B_fgs()
B_all = B.get_B()

In [43]:
print(B_all)

[[1.         0.         1.        ]
 [1.         0.15071531 1.42538127]
 [1.         0.20273315 1.91733692]
 [1.         0.49714796 4.70174773]
 [1.         1.         0.        ]]


#### Update parameters of the Mixing Matrix

In [44]:
new_params = B.params+1
B.update_params(new_params)
B.params

array([[1.15071531, 2.42538127],
       [1.20273315, 2.91733692],
       [1.49714796, 5.70174773]])

In [45]:
B_all_new = B.get_B()
B_all_new

array([[1.        , 0.        , 1.        ],
       [1.        , 1.15071531, 2.42538127],
       [1.        , 1.20273315, 2.91733692],
       [1.        , 1.49714796, 5.70174773],
       [1.        , 1.        , 0.        ]])