## Tutorial on how to use the Mixing Matrix

In [1]:
import numpy as np
from micmac import *

#### Set required parameters
(In actual applications they'll come from the instrument / input data)

In [2]:
# nside of input freq maps
NSIDE = 64
# choose frequencies
freqs = np.array([40, 50, 60, 100, 140])
# choose number of components
ncomp = 3
# choose frequencies at which we have one fgs and the others zero
# in MixingMat columns first synch, then dust
pos_special_freqs = np.array([0, -1])
# number of parameters in the MixingMat
n_betas = (ncomp-1)*(len(freqs)-ncomp+1)

#### Get spv tree

In [3]:
yaml_file_path = 'params_spv_tutorial.yaml'
root_tree = tree_spv_config(yaml_file_path, n_betas, print_tree=True)
nodes_b = get_nodes_b(root_tree)

6
root
  nside_spv
    default: [4]
    f1
      default: [4]
      b1
        default: [32]
      b2
        default: [8]
      b3
        default: [4]
    f2
      default: [4]
      b1
        default: [32]
      b2
        default: [8]
      b3
        default: [4]


#### Initialize parameters of the Mixing Matrix
These are the true values (done with values coming from SEDs of a MBB and a PL).
Alternativly one can skip this step and set customized values.

In [9]:
initB = InitMixingMatrix(freqs, ncomp, pos_special_freqs, nodes_b)
init_params = initB.init_params()
init_params
for i in init_params:
    print(i)

0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001699259
0.5204473001

#### Build the Mixing Matrix

In [5]:
B = MixingMatrix(freqs, ncomp, nodes_b, NSIDE, init_params, pos_special_freqs)
B_cmb = B.get_B_cmb()
B_fgs = B.get_B_fgs()
B_all = B.get_B()

node:  f1 b1
>>> Creating new template for:  [32]
node:  f1 b2
>>> Creating new template for:  [8]
node:  f1 b3
>>> Creating new template for:  [4]
node:  f2 b1
>>> Creating new template for:  [32]
node:  f2 b2
>>> Creating new template for:  [8]
node:  f2 b3
>>> Creating new template for:  [4]
node:  f1 b1
>>> Creating new template for:  [32]
node:  f1 b2
>>> Creating new template for:  [8]
node:  f1 b3
>>> Creating new template for:  [4]
node:  f2 b1
>>> Creating new template for:  [32]
node:  f2 b2
>>> Creating new template for:  [8]
node:  f2 b3
>>> Creating new template for:  [4]


In [11]:
print(B_all)

[[[1.         1.         1.         ... 1.         1.         1.        ]
  [1.         1.         1.         ... 1.         1.         1.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]]

 [[1.         1.         1.         ... 1.         1.         1.        ]
  [0.5204473  0.5204473  0.5204473  ... 0.5204473  0.5204473  0.5204473 ]
  [0.09568486 0.09568486 0.09568486 ... 0.09568486 0.09568486 0.09568486]]

 [[1.         1.         1.         ... 1.         1.         1.        ]
  [0.30561537 0.30561537 0.30561537 ... 0.30561537 0.30561537 0.30561537]
  [0.17041835 0.17041835 0.17041835 ... 0.17041835 0.17041835 0.17041835]]

 [[1.         1.         1.         ... 1.         1.         1.        ]
  [0.06122007 0.06122007 0.06122007 ... 0.06122007 0.06122007 0.06122007]
  [0.49067474 0.49067474 0.49067474 ... 0.49067474 0.49067474 0.49067474]]

 [[1.         1.         1.         ... 1.         1.         1.        ]
  [0.         0.         0.   

#### Update parameters of the Mixing Matrix

In [7]:
new_params = B.params+1
B.update_params(new_params)
B.get_params_long()

node:  f1 b1
>>> Creating new template for:  [32]
node:  f1 b2
>>> Creating new template for:  [8]
node:  f1 b3
>>> Creating new template for:  [4]
node:  f2 b1
>>> Creating new template for:  [32]
node:  f2 b2
>>> Creating new template for:  [8]
node:  f2 b3
>>> Creating new template for:  [4]


array([[[1.5204473 , 1.5204473 , 1.5204473 , ..., 1.5204473 ,
         1.5204473 , 1.5204473 ],
        [1.09568486, 1.09568486, 1.09568486, ..., 1.09568486,
         1.09568486, 1.09568486]],

       [[1.30561537, 1.30561537, 1.30561537, ..., 1.30561537,
         1.30561537, 1.30561537],
        [1.17041835, 1.17041835, 1.17041835, ..., 1.17041835,
         1.17041835, 1.17041835]],

       [[1.06122007, 1.06122007, 1.06122007, ..., 1.06122007,
         1.06122007, 1.06122007],
        [1.49067474, 1.49067474, 1.49067474, ..., 1.49067474,
         1.49067474, 1.49067474]]])

In [8]:
B_all_new = B.get_B()
B_all_new

node:  f1 b1
>>> Creating new template for:  [32]
node:  f1 b2
>>> Creating new template for:  [8]
node:  f1 b3
>>> Creating new template for:  [4]
node:  f2 b1
>>> Creating new template for:  [32]
node:  f2 b2
>>> Creating new template for:  [8]
node:  f2 b3
>>> Creating new template for:  [4]


array([[[1.        , 1.        , 1.        , ..., 1.        ,
         1.        , 1.        ],
        [1.        , 1.        , 1.        , ..., 1.        ,
         1.        , 1.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[1.        , 1.        , 1.        , ..., 1.        ,
         1.        , 1.        ],
        [1.5204473 , 1.5204473 , 1.5204473 , ..., 1.5204473 ,
         1.5204473 , 1.5204473 ],
        [1.09568486, 1.09568486, 1.09568486, ..., 1.09568486,
         1.09568486, 1.09568486]],

       [[1.        , 1.        , 1.        , ..., 1.        ,
         1.        , 1.        ],
        [1.30561537, 1.30561537, 1.30561537, ..., 1.30561537,
         1.30561537, 1.30561537],
        [1.17041835, 1.17041835, 1.17041835, ..., 1.17041835,
         1.17041835, 1.17041835]],

       [[1.        , 1.        , 1.        , ..., 1.        ,
         1.        , 1.        ],
        [1.06122007, 1.06122007, 1