## Tutorial on how to use the Mixing Matrix

In [1]:
import numpy as np
from micmac import *

#### Set required parameters
(In actual applications they'll come from the instrument / input data)

In [2]:
# choose frequencies
freqs = np.array([40, 50, 60, 100, 140])
# choose number of components
ncomp = 3
# choose frequencies at which we have one fgs and the others zero
# in MixingMat columns first synch, then dust
pos_special_freqs = np.array([0, -1])

#### Initialize parameters of the Mixing Matrix
These are the true values (done with values coming from SEDs of a MBB and a PL).
Alternativly one can skip this step and set customized values.

In [3]:
initB = InitMixingMatrix(freqs, ncomp, pos_special_freqs)
init_params = initB.init_params()
init_params

array([[0.5204473 , 0.09568486],
       [0.30561537, 0.17041835],
       [0.06122007, 0.49067474]])

#### Build the Mixing Matrix

In [4]:
B = MixingMatrix(freqs, ncomp, init_params, pos_special_freqs)
B_cmb = B.get_B_cmb()
B_fgs = B.get_B_fgs()
B_all = B.get_B()

In [5]:
print(B_all)

[[1.         1.         0.        ]
 [1.         0.5204473  0.09568486]
 [1.         0.30561537 0.17041835]
 [1.         0.06122007 0.49067474]
 [1.         0.         1.        ]]


#### Update parameters of the Mixing Matrix

In [6]:
new_params = B.params+1
B.update_params(new_params)
B.params

array([[1.5204473 , 1.09568486],
       [1.30561537, 1.17041835],
       [1.06122007, 1.49067474]])

In [7]:
B_all_new = B.get_B()
B_all_new

array([[1.        , 1.        , 0.        ],
       [1.        , 1.5204473 , 1.09568486],
       [1.        , 1.30561537, 1.17041835],
       [1.        , 1.06122007, 1.49067474],
       [1.        , 0.        , 1.        ]])